# --- Defaults ---

# --- pymarl options ---
runner: "episode" # Runs 1 env for an episode
mac: "basic_mac" # Basic controller
env: "sc2" # Environment name
#env: "hok"
env_args: {} # Arguments for the environment
batch_size_run: 1 # Number of environments to run in parallel
test_nepisode: 3 # Number of episodes to test for
test_interval: 20000 # Test after {} timesteps have passed
test_greedy: True # Use greedy evaluation (if False, will set epsilon floor to 0
log_interval: 1000 # Log summary of stats after every {} timesteps
runner_log_interval: 2000 # Log runner stats (not test stats) every {} timesteps
learner_log_interval: 2000 # Log training stats every {} timesteps
t_max: 10000 # Stop running after this many timesteps
use_cuda: True # Use gpu by default unless it isn't available
buffer_cpu_only: True # If true we won't keep all of the replay buffer in vram

# --- Logging options ---
use_tensorboard: False # Log results to tensorboard
save_model: True # Save the models to disk
save_model_interval: 10000 # Save models after this many timesteps
# checkpoint_path: "/home/ubuntu/Hok_Marl_ppo/results/models/mappo_env_1__2024-04-24_00-38-09/673574" # Load a checkpoint from this path
# checkpoint_path: "/home/ubuntu/Hok_Marl_ppo/results/models/mappo_env_adjustpolicy_loss__2024-05-12_23-38-47/905829" ## 初步有效果，在这个基础上继续训 # 能打出赢蓝方的操作
# checkpoint_path: "/home/ubuntu/Hok_Marl_ppo/results/models/mappo_env_adjustpolicy_loss__2024-05-12_23-38-47/1198" # 最开始的模型
# checkpoint_path: "/home/ubuntu/Hok_Marl_ppo/results/models/mappo_env_adjustpolicy_loss_withmodel2__2024-05-13_18-53-57/191321" # 最新的模型
# checkpoint_path: "/home/ubuntu/Hok_Marl_ppo/results/models/mappo_env_adjustpolicy_loss_withmodel2__2024-05-13_18-53-57/233303" # 总是红方无弹
# checkpoint_path: "/home/ubuntu/Hok_Marl_ppo/results/models/lyz_508982_adjustreward" # lyz的调整reward后的模型 #
checkpoint_path: ""
evaluate: False # Evaluate model for test_nepisode episodes and quit (no training)
load_step: 0 # Load model trained on this many timesteps (0 if choose max possible)
save_replay: False # Saving the replay of the model loaded from checkpoint_path
local_results_path: "results" # Path for local results

# --- RL hyperparameters ---
gamma: 0.99
batch_size: 32 # Number of episodes to train on
buffer_size: 32 # Size of the replay buffer
lr: 0.0005 # Learning rate for agents
critic_lr: 0.0005 # Learning rate for critics
optim_alpha: 0.99 # RMSProp alpha
optim_eps: 0.00001 # RMSProp epsilon
grad_norm_clip: 10 # Reduce magnitude of gradients above this L2 norm
# hc
add_value_last_step: True

# --- Agent parameters ---
agent: "rnn" # Default rnn agent
rnn_hidden_dim: 128 # Size of hidden state for default rnn agent
obs_agent_id: True # Include the agent's one_hot id in the observation
obs_last_action: True # Include the agent's last action (one_hot) in the observation

# --- Experiment running params ---
repeat_id: 1
label: "default_label"

run: "default"
